"""Build the web prototype.

    python3 web/build.py

1. Exports data/*.json to web/js/data.js (so the game works from file:// too).
2. Writes web/dist/dockside.html: one self-contained page (CSS and JS inlined) used for
   the shareable playable link. The Artifact host adds <!doctype>, <html>, <head>, <body>,
   so the dist file contains only the page content.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
FILES = ["config", "containers", "items", "upgrades", "collections", "rivals", "contracts"]
SCRIPTS = ["js/data.js", "js/core/rules.js", "js/core/game.js", "js/ui/audio.js", "js/ui/scene.js", "js/ui/ui.js", "js/main.js"]


def export_data():
    bundle = {}
    for name in FILES:
        with open(os.path.join(DATA, name + ".json"), encoding="utf-8") as f:
            bundle[name] = json.load(f)
    body = json.dumps(bundle, ensure_ascii=False, separators=(",", ":"))
    with open(os.path.join(HERE, "vendor", "game-icons-subset.json"), encoding="utf-8") as f:
        icons = json.dumps(json.load(f), ensure_ascii=False, separators=(",", ":"))
    out = os.path.join(HERE, "js", "data.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("/* Generated by web/build.py from data/*.json and web/vendor. Do not edit. */\n")
        f.write("window.DOCKSIDE_DATA = " + body + ";\n")
        f.write("/* Icons: game-icons.net (Lorc, Delapouite and contributors), CC BY 3.0. */\n")
        f.write("window.DOCKSIDE_ICONS = " + icons + ";\n")
    return out


def read(rel):
    with open(os.path.join(HERE, rel), encoding="utf-8") as f:
        return f.read()


def build_single():
    html = read("index.html")
    head = re.search(r"<head>(.*?)</head>", html, re.S).group(1)
    body = re.search(r"<body>(.*?)</body>", html, re.S).group(1)
    head = re.sub(r'<meta charset="utf-8">\s*', "", head)
    head = re.sub(r'<meta name="viewport"[^>]*>\s*', "", head)
    head = head.replace('<link rel="stylesheet" href="css/style.css">', "<style>\n" + read("css/style.css") + "</style>")
    scripts = "\n".join("<script>\n" + read(s).replace("</script", "<\\/script") + "\n</script>" for s in SCRIPTS)
    body = re.sub(r"<!-- BUILD:SCRIPTS -->.*<!-- /BUILD:SCRIPTS -->", lambda _m: scripts, body, flags=re.S)
    os.makedirs(os.path.join(HERE, "dist"), exist_ok=True)
    out = os.path.join(HERE, "dist", "dockside.html")
    with open(out, "w", encoding="utf-8") as f:
        f.write(head.strip() + "\n" + body.strip() + "\n")
    return out


if __name__ == "__main__":
    print("wrote", os.path.relpath(export_data(), ROOT))
    print("wrote", os.path.relpath(build_single(), ROOT))
